### PR TITLE
docs: Set autoread for vim integration to get the buffer to automatically reload

### LINKED ISSUE #81: Vim integration docs may want to mention that it requires autoread
I had to set `autoread` in order to get vim to automatically reload the buffer after applying the autocmd.

### PR DESCRIPTION
**Pull request by shangxiao**
Resolves #81

### CODE REVIEW

**Comment by akaihola** [comment]
Hi @shangxiao, big thanks for this patch!

The build is failing due to a Pytest/Mypy related problem on Python 3.8. I fixed that in #83. Once that PR has been merged, let's rebase this one on `master` and get the tests to pass.

Would you like to review #83?

**Comment by akaihola** [comment]
@shangxiao, I think this MR is still good! Could you rebase on `master` to trigger the build in GitHub Actions?

**Comment by ivanov** [comment]
@akaihola I believe that another way to re-trigger the build should be to close the PR and reopen it. I'm gonna try that now.

**Review by ivanov — APPROVED** [review]
I think the Travis failure is a remnant of the past here. We should merge either this PR or the equivalent #96

**Comment by akaihola** [comment]
#96 was merged and resolved this issue.

**Pull request closed without merging**
