### PR TITLE
(bump_version) Milestones can have an additional comment

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
I think the remaining issue is there are multiple variants of a dash. Therefore the first split doesn't do anything.

**Comment by MatthijsBurgh** [comment]
I changed the milestones to use the short dash. But a rerun results in the same behaviour.

**Comment by MatthijsBurgh** [comment]
I changed the milestones to include a short dash. Now the the script does it thing. I can't say it is the correct behaviour, but that is up to you.

**Comment by MatthijsBurgh** [comment]
I changed the milestones to include a short dash. Now the the script does it thing. I can't say it is the correct behaviour, but that is up to you.

**Review by akaihola — APPROVED** [review]

**Comment by akaihola** [comment]
Thanks @MatthijsBurgh!

**Pull request merged**
