### PR TITLE
Document how to pin reformatters/linters in pre-commit configuration

### LINKED ISSUE #426: Document how to specify Black version when using a pre-commit hook
>@victorcui96, I think each pre-commit hook installs into its own environment so modifying your project's requirements.txt will have no effect. The above referencing issue has a fix though, so applying that in your pre commit config would look like:
>
>```
>  - repo: https://github.com/akaihola/darker
>    rev: 1.5.1
>    hooks:
>      - id: darker
>        args:
>           - --line-length=120
>        language_version: python3
>        additional_dependencies: [black==22.10.0]
>```

_Originally posted by @leej3 in https://github.com/akaihola/darker/issues/412#issuecomment-1350785028_

### PR DESCRIPTION
**Pull request by akaihola**
Fixes #426.

### CODE REVIEW

**Comment by akaihola** [comment]
Could one of you review this addition to documentation @wpnbos @k-dominik @victorcui96 @jedie @leej3? Thanks!

**Review by k-dominik — APPROVED** [review]
The update to the docs (and darker in general) is highly appreciated :)! I definitely know how to pin things after reading it.

The only thing that I noticed are the different indentation sizes/styles used in different portions of the Readme.

**Comment by akaihola** [comment]
@k-dominik, by different indentations, are you referring to YAML snippets?

**Comment by akaihola** [comment]
I now unified YAML formatting in `README.rst`.

**Pull request merged**
