### PR TITLE
Rely on rST option list support

### PR DESCRIPTION
**Pull request by flying-sheep**
rST has built in support for option lists, maybe we should use it?

### CODE REVIEW

**Comment by akaihola** [comment]
Neat, I didn't know about that!

This is how it renders for me on GitHub:
image

The table seems to follow the layout of the reST source – short options are in the leftmost column with the description in the rightmost one. Longer options are on their own row, and the leftmost column is empty on the following row with the description in the rightmost one. This looks a bit incostintent to me. Is there any other way to get the options always in the leftmost column than to indent and squeeze descriptions to the right of the options in the reST source?

Also, you've kept the original single-backtick highlighting from `darker --help` (for e.g. package names). GitHub doesn't format these differently at all – we probably need to use double backticks, right?

The single drawback from using this format and customizing it is that it's no longer possible to do a straight copy-paste from `darker --help` to `README.rst` whenever options have been modified. But that's arguably an acceptable trade-off for the more pleasing look for the eye.

**Comment by flying-sheep** [comment]
> Is there any other way to get the options always in the leftmost column than to indent and squeeze descriptions to the right of the options in the reST source?

It directly mirrors the source code. Long options are written as

```rst
-S, --skip-string-normalization
                      Don't normalize string quotes or prefixes
```

and short ones as

```rst
-i, --isort           Also sort imports using the `isort` package
```

so I assume indenting everything until even the longest options fit would achieve what you want.

> The single drawback from using this format and customizing it is that it's no longer possible to do a straight copy-paste from `darker --help` to `README.rst` whenever options have been modified.

Doing `ArgumentParser(..., formatter_class=lambda **kwargs: NewlinePreservingFormatter(**kwargs, max_help_position=float('inf')))` works!

**Comment by akaihola** [comment]
@flying-sheep, I'm experimenting with code for generating the list of options in the format discussed above. Let me commit it to this branch so we can review if it makes sense.

**Comment by akaihola** [comment]
There you go, `darker --options-for-readme` should now output the list of options in a format which can be copy-pasted as such into `README.rst`. It wasn't super straightforward to get this, it required using some `argparse` internals. But it works...

**Comment by akaihola** [comment]
...however, what the hell, it still renders like this:
image

So probably GitHub's renderer makes its own calls for how to display long options!

**Comment by flying-sheep** [comment]
huh, seems like it! or even docutils … too bad!

**Comment by akaihola** [comment]
Yes, and also if we write options on their own line with description starting indented on the next line, GitHub and docutils will still keep the rendering same.

I guess let's live with that.

The test failures will be fixed by #190.

**Comment by flying-sheep** [comment]
do you prefer squash & merge or a merge commit?

**Comment by akaihola** [comment]
My workflow has been to rebase feature branches on `master` and sometimes reorganize the commits to get rid of extra back-and-forths and trials and errors. I then do a `--no-ff` merge commit to preserve the feature branch and its commits in the repository history.

But that's not a hard requirement, I don't want to be too strict on this.

**Review by akaihola — APPROVED** [review]
This is a nice clean-up for the README. We could even add CI automation for updating (or at least verifying) the command line usage in README. But this is a great first step!

**Pull request merged**
