### PR TITLE
Fix typo in pylint example, unmatched " Update README.rst

### PR DESCRIPTION
**Pull request by clintonsteiner**
Change: `--lint="pylint --ignore='setup.py'""` to `--lint="pylint --ignore='setup.py'"` to be correct

### CODE REVIEW

**Review by khaled5321 — APPROVED** [review]

**Review by MatthijsBurgh — APPROVED** [review]

**Comment by clintonsteiner** [comment]
Hello @MatthijsBurgh 
I appreciate you taking the time to review my PR.
Any advice on getting the github actions to kickoff?

Oddly enough I did the same thing on my fork and they ran immediately.

**Comment by clintonsteiner** [comment]
Looks like the other two PR's haven't had the actions kickoff either. Let me know if I should open up an issue
https://github.com/akaihola/darker/pull/519
https://github.com/akaihola/darker/pull/515

**Comment by MatthijsBurgh** [comment]
We need @akaihola for the CI

**Comment by akaihola** [comment]
> We need @akaihola for the CI

I guess I didn't react in time. I can't find how to re-run the checks now. Any insight?

**Comment by MatthijsBurgh** [comment]
I have no clue why the CI is not being run.

**Review by akaihola — APPROVED** [review]

**Pull request merged**
