### PR TITLE
Run CI on Windows

### PR DESCRIPTION
**Pull request by martinRenou**
Also changing the config so that the CI runs for all PRs, if that is ok for you.

### CODE REVIEW

**Review by akaihola — APPROVED** [review]

**Comment by martinRenou** [comment]
I will try to find time to understand the Windows issue. Maybe you should not merge this PR until the Windows issue is fixed.

**Comment by akaihola** [comment]
@martinRenou looks like the Windows installation issue is about file encodings. Could you make an issue here about it? Let's work on it there.

**Comment by martinRenou** [comment]
Sure!

**Comment by martinRenou** [comment]
@akaihola the installation issue seems to be fixed correctly with https://github.com/akaihola/darker/pull/123. It is now failing in tests, but this would require a different fix.

**Review by akaihola — APPROVED** [review]

**Comment by akaihola** [comment]
Yes, it seems `TextDocument.from_file()` does transparent conversion of Windows newlines into Unix newlines when reading source code files. On Unix, Windows newlines are kept intact by Python and by Darker. I'll create a separate issue for this.

**Comment by akaihola** [comment]
I fixed the test failures in #125. Could you @martinRenou review that one? After it's merged, you could rebase this one on `master` and tests should then pass on Windows, too.

**Comment by martinRenou** [comment]
@akaihola rebased and green :)

**Comment by akaihola** [comment]
Thanks @martinRenou, this was an important contribution!

**Pull request merged**
