### PR TITLE
Upgrade GitHub Action checkout

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/actions/checkout/releases

### CODE REVIEW

**Comment by akaihola** [comment]
Hi @cclauss, thanks for the heads-up on this!

The build is failing due to the updated `flake8-bugbear` plugin complaining about our use of `@lru_cache`. This is being fixed in #340. Please wait for that to be merged (review appreciated!) and then rebase this one on top of `master`. That should fix the failure.

**Comment by roniemartinez** [comment]
@akaihola You can use dependabot module and actions update

**Comment by akaihola** [comment]
Last time I tried out dependabot it didn't understand `setup.cfg` files. Maybe that's fixed now? And I didn't know it does actions as well!

**Review by brtknr — APPROVED** [review]

**Comment by akaihola** [comment]
Thanks @cclauss and @brtknr!

**Pull request merged**
